version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
     - MONGO_INITDB_ROOT_USERNAME: joel
     - MONGO_INITDB_ROOT_PASSWORD: password
    volumes: 
      - ./database:/data/db
      - ./ddl:/ddl


  db: 
    build:
      context: .
    volumes:
      - ./utils:/db
      - ./devLogs:/logs
    ports:
      - '3000:3000'
    depends_on:
    - 'mongo'
    environment:
      - NODE_ENV
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGODB_URI


