version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    environment:
     - MONGO_INITDB_ROOT_USERNAME
     - MONGO_INITDB_ROOT_PASSWORD
    volumes: 
      - ./database:/data/db

  ecommerce: 
    build:
      context: .
    volumes:
      - ./utils:/db
      - ./devLogs:/logs
    ports:
      - '3001:3000'
    depends_on:
    - 'mongo'
    environment:
      - NODE_ENV
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGODB_URI


