version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    environment:
     - MONGO_INITDB_ROOT_USERNAME
     - MONGO_INITDB_ROOT_PASSWORD
    volumes: 
      - ./database:/data/db
    ports:
      - '27017:27017'

  ecommerce: 
    build:
      context: .
    volumes:
      - ./pages:/pages/app
      - ./devLogs:/logs
    ports:
      - '3001:3000'
    depends_on:
    - 'mongo'
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGODB_URI



